name: CompressibleBlocks
version: ${project.version}
main: dev.giovalgas.compressibleblocks.CompressibleBlocks
api-version: 1.16
commands:
  compressibleblocks:
    aliases: ["cp"]
    usage: "/compressibleblocks <args>"
    description: "CompressibleBlocks plugin main command"